#!/bin/bash

# set this to the location where the script is
CUR_DIR="$HOME/.config/lock/blur"

# this script will run slow at first time because it is generating a blurred image
# after that it will run fast because it save the blurred image

# Image you want to set as a background
# If you are using the script for first time or are using new image
# pass -gen to script
# or delete the blurred image generated by the script
image1="$CUR_DIR/wallpaper.png"

if [ ! -f "$image1" ]; then
    echo "Image $image1 do not exists..."
    exit 1
fi

# This will be the image produced after processing the image1
# this image will be saved for faster startup time
# because if we run blurr command everyting it will delay the
# startup time
image="$CUR_DIR/blurred.png"

# INITIAL OPTIONS
font="VictorMono Nerd Font"
hue=(-level "0%,100%,0.6")
effect=(-filter Gaussian -resize 20% -define "filter:sigma=1.5" -resize 500.5%)
bw="white"
resol="1920x1080"
icon="$CUR_DIR/icons/lock.png"
font_color="#000000"

# choose the lock color
value="60" #brightness value to compare to
# take some part of image and process it to check it's contrast so that we can use either
# black lock or white lock
color=$(convert "$image1" -gravity center -crop 100x100+0+0 +repage -colorspace hsb \
    -resize 1x1 txt:- | awk -F '[%$]' 'NR==2{gsub(",",""); printf "%.0f\n", $(NF-1)}')
if [[ $color -gt $value ]]; then #white background image and black text
    bw="black"
    icon="$CUR_DIR/icons/lockdark.png"
    param=("--inside-color=0000001c" "--ring-color=0000003e"
        "--line-color=00000000" "--keyhl-color=ffffff80" "--ringver-color=ffffff00"
        "--separator-color=22222260" "--insidever-color=ffffff1c"
        "--ringwrong-color=ffffff55" "--insidewrong-color=ffffff1c"
        "--verif-color=ffffff00" "--wrong-color=ff000000" "--time-color=ffffff00"
        "--date-color=ffffff00" "--layout-color=ffffff00")
    font_color="#000000"
else #black background image and white text
    bw="white"
    icon="$CUR_DIR/icons/lock.png"
    param=("--inside-color=ffffff1c" "--ring-color=ffffff3e"
        "--line-color=ffffff00" "--keyhl-color=00000080" "--ringver-color=00000000"
        "--separator-color=22222260" "--insidever-color=0000001c"
        "--ringwrong-color=00000055" "--insidewrong-color=0000001c"
        "--verif-color=00000000" "--wrong-color=ff000000" "--time-color=00000000"
        "--date-color=00000000" "--layout-color=00000000")
    font_color="#ffffff"
fi

if [ ! -f "$image" ] || [[ "$1" == "-gen" ]]; then
    echo "Generating the blurred image..."
    convert "$image1" -resize "$resol" "${hue[@]}" "${effect[@]}" -pointsize 26 -fill "$bw" -gravity center \
        "$icon" -gravity center -composite "$image"
fi

i3lock -i "$image" "${param[@]}" --ignore-empty-password \
    --clock \
    --time-color=$font_color \
    --time-str="Locked" \
    --time-font="$font" \
    --time-size=30 \
    --time-pos="953:700" \
    --verif-font="$font" \
    --verif-size=30 \
    --verif-text="Verifying..." \
    --verif-pos="953:700" \
    --verif-color=$font_color \
    --wrong-font="$font" \
    --wrong-size=30 \
    --wrong-text="Invalid Password" \
    --wrong-pos="953:700" \
    --wrong-color=$font_color \
    --no-modkey-text
