#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x polybar > /dev/null || ~/.config/polybar/launch.sh

# bspc monitor -d I II III IV V VI VII VIII IX X
# "一","二","三","四","五","六","七","八","九","十"
bspc monitor -d 1 2 3 4 5

bspc config border_width          0
bspc config window_gap            14
bspc config split_ratio           0.52
bspc config ignore_ewmh_focus     true

bspc config borderless_monocle    true
bspc config gapless_monocle       false
bspc config focus_follows_pointer false

bspc rule -a "YouTube Music" desktop='^5' state=fullscreen
bspc rule -a Zathura state=tiled
bspc rule -a mpv state=fullscreen
bspc rule -a Nsxiv state=fullscreen
bspc rule -a Lxappearance focus=on follow=on state=floating
bspc rule -a kdeconnect.app state=floating
bspc rule -a Anki state=floating
bspc rule -a Mechvibes state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Pick-colour-picker state=floating
bspc rule -a Steam state=floating
rule rule -a eww floating=on center=on

# bspc subscribe node_state | while read -r _ _ _ _ state flag; do
#     if [ "$state" != "fullscreen" ]; then
#         continue
#     fi

#     ~/.config/eww/bar/launch_bar
# done &

# bspc config normal_border_color     "#ffffff"
# bspc config focused_border_color    "#5E81AC"
# bspc config presel_feedback_color   "#000000"
