#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x polybar > /dev/null || ~/.config/polybar/launch.sh

# bspc monitor -d I II III IV V VI VII VIII IX X
# "一","二","三","四","五","六","七","八","九","十"
bspc monitor -d I II III IV V

bspc config border_width         0
bspc config window_gap           14

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config focus_follows_pointer false

bspc rule -a "YouTube Music" desktop='^5' state=fullscreen
bspc rule -a Zathura state=tiled
bspc rule -a mpv state=fullscreen
bspc rule -a Nsxiv state=fullscreen
bspc rule -a Lxappearance focus=on follow=on state=floating
bspc rule -a kdeconnect.app state=floating
bspc rule -a Pick-colour-picker state=floating

# bspc config normal_border_color     "#ffffff"
# bspc config focused_border_color    "#5E81AC"
# bspc config presel_feedback_color   "#000000"
# 


# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
