#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
~/.config/polybar/launch.sh

# feh --bg-fill --randomize /mnt/WindowsD/Sanchay/Pictures/Space/*
feh --bg-fill --randomize /mnt/WindowsD/Sanchay/Pictures/favs/*

bspc monitor -d I II III IV V VI VII VIII IX X XI

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a "YouTube Music" desktop='^10'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled

bspc config normal_border_color     "#2E3440"
bspc config focused_border_color    "#4C566A"
bspc config presel_feedback_color   "#4C566A"
