#!/bin/bash

# pactl set-sink-volume @DEFAULT_SINK@ {+,-}1% && dunstify -h string:x-dunst-stack-tag:pulseaudio "Volume" -h int:value:"`pactl list sinks | grep '^[[:space:]]Volume:' | head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,'`"

dir="$HOME/.config/icons"

function get_volume {
    pactl list sinks | grep '^[[:space:]]Volume:' | head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,'
    # amixer get Master | grep '%' | head -n 1 | cut -d '[' -f 2 | cut -d '%' -f 1
}

function is_mute {
    pacmd list-sinks | awk '/muted/ { print $2 }'
    # amixer get Master | grep '%' | grep -oE '[^ ]+$' | grep off > /dev/null
}

function send_notification {
    cur=$(get_volume)

    if [ $(is_mute) = "yes" ] ; then
        icon="$dir/volume-muted.svg"
    else
        if [ "$cur" -lt "15" ]; then
            icon="$dir/volume-low.svg"
        elif [ "$cur" -lt "50" ]; then
            icon="$dir/volume-medium.svg"
        else
            icon="$dir/volume-high.svg"
        fi
    fi

    dunstify -h string:x-dunst-stack-tag:pulseaudio "Volume" -h int:value:"$cur" -i $icon -u normal

    # bar=$(seq --separator="─" 0 "$((cur / 5))" | sed 's/[0-9]//g')
    # dunstify "Volume" "$bar" -i $icon -u normal
}

case $1 in
    up)
        pactl set-sink-volume @DEFAULT_SINK@ +5% > /dev/null
        # amixer -D pulse set Master on > /dev/null
        # amixer -D pulse sset Master 5%+ > /dev/null
        send_notification
        ;;
    down)
        pactl set-sink-volume @DEFAULT_SINK@ -5% > /dev/null
        # amixer -D pulse set Master on > /dev/null
        # amixer -D pulse sset Master 5%- > /dev/null
        send_notification
        ;;
    mute)
        pactl set-sink-mute @DEFAULT_SINK@ toggle > /dev/null
        # amixer -D pulse set Master 1+ toggle > /dev/null
        send_notification
        ;;
    micmute)
        pactl set-source-mute @DEFAULT_SOURCE@ toggle
        ;;
esac
