#!/bin/sh

BROWSER=google-chrome-beta

[ -z "$1" ] && { "$BROWSER"; exit; }

case "$1" in
	# *mkv|*webm|*mp4|*youtube.com/watch*|*youtube.com/playlist*|*youtu.be*|*odysee.com*)
		# setsid -f mpv -quiet "$1" >/dev/null 2>&1 ;;
	*png|*jpg|*jpeg|*gif)
        curl -sL "$1" > "$HOME/pix/tmp/$(echo "$1" | sed "s/.*\///;s/%20/ /g")" && nsxiv -a "$HOME/pix/tmp/$(echo "$1" | sed "s/.*\///;s/%20/ /g")" >/dev/null 2>&1 & ;;
	*pdf|*cbz|*cbr)
		curl -sL "$1" > "$HOME/docs/$(echo "$1" | sed "s/.*\///;s/%20/ /g")" && zathura "$HOME/docs/$(echo "$1" | sed "s/.*\///;s/%20/ /g")" >/dev/null 2>&1 & ;;
	# *mp3|*flac|*opus|*mp3?source*)
		# qndl "$1" 'curl -LO'  >/dev/null 2>&1 ;;
	*)
		[ -f "$1" ] && setsid -f "$TERMINAL" -e "$EDITOR" "$1" >/dev/null 2>&1 || setsid -f "$BROWSER" "$1" >/dev/null 2>&1
esac
