#!/usr/bin/env bash

uptime=$(uptime -p | sed -e 's/up //g')

shutdown="󰐥  Shut down"
reboot="󰜉  Restart"
lock="󰌾  Lock"
suspend="󰤄  Sleep"
logout="󰍃  Logout"

chosen="$(echo -e "$logout\n$lock\n$suspend\n$shutdown\n$reboot" | rofi -theme ~/.config/rofi/powermenu.rasi -p "Uptime: $uptime" -dmenu -i -selected-row 0)"

case $chosen in
    $shutdown)
        systemctl poweroff ;;
    $reboot)
        systemctl reboot ;;
    $lock)
         betterlockscreen -l ;;
    $suspend)
        mpc -q pause
        amixer set Master mute
        systemctl suspend ;;
    $logout)
        if [[ "$DESKTOP_SESSION" == "bspwm" ]]; then
            bspc quit
        elif [[ "$DESKTOP_SESSION" == "i3" ]]; then
            i3-msg exit
        fi ;;
esac
