#!/bin/bash

a="MonkeyType"
b="Codeforces"
c="WhatsApp"
d="Contests"
e="Hacker News"
f="CSES Problem Set"
g="LeetCode"
h="YouTube"
i="Reddit"
j="CP"
k="CodeChef"
l="AtCoder"
m="TypeRacer"
n="10 Fast Fingers"


chosen="$(echo -e "$a\n$b\n$c\n$d\n$e\n$f\n$g\n$h\n$i\n$j\n$k\n$l\n$m\n$n" | rofi -theme ~/.config/rofi/slate1.rasi -dmenu -i)"

case $chosen in
    $a)
        google-chrome-beta --new-window --app="https://monkeytype.com" ;;
    $b)
        google-chrome-beta --new-window --app="https://codeforces.com" ;;
    $c)
        google-chrome-beta --new-window --app="https://web.whatsapp.com/" ;;
    $d)
        google-chrome-beta --new-window --app="https://clist.by/" ;;
    $e)
        google-chrome-beta --new-window --app="https://news.ycombinator.com/" ;;
    $f)
        google-chrome-beta --new-window --app="https://cses.fi/problemset/" ;;
    $g)
        google-chrome-beta --new-window --app="https://leetcode.com/" ;;
    $h)
        google-chrome-beta "https://www.youtube.com/" ;;
    $i)
        google-chrome-beta "https://www.reddit.com/" ;;
    $j)
        dolphin --new-window /mnt/WindowsD/Sanchay/Study/CP/ ;;
    $k)
        google-chrome-beta --new-window --app="https://www.codechef.com/" ;;
    $l)
        google-chrome-beta --new-window --app="https://atcoder.jp/" ;;
    $m)
        google-chrome-beta --new-window --app="https://play.typeracer.com/" ;;
    $n)
        google-chrome-beta --new-window --app="https://10fastfingers.com/" ;;
esac
